name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage", "needs"]
assignees:
  - cnjimbo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2.5.*
        - 2.4.*
        - 2.3.*
        - 2.2.*
        - 2.1.*
        - 2.0.*       
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value:
        Tell us what you see!


        **// Current Behavior


        **// Expected Behavior
      
    validations:
      required: true

  - type: textarea
    id: source-destination-types
    attributes:
      label:  Source/destination types and Mapping configuration
      description: Please copy and paste all c# code related Source/destination types and Mapping configuration.
                   also tell us any code if that impact the configuration of mapping
                   粘贴mapping中的源/目标对象的类型和mapper配置。这将自动格式化为C#代码。
      placeholder: // Put your source/destination types and getting mapper code here
      render: csharp

  - type: textarea
    id: calling-mapper-methods
    attributes:
      label: Your calls to Mapper.Map , with source/destination objects constructed
      description: Please copy and paste any relevant c# code. 这将自动格式化为C#代码。
      render: csharp





          