name: compile & test & publish
on:
  push:
    branches:
      [ master ]
  pull_request:
    branches: [ master ] # Default release branch
  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
        
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 3.1.* 
        uses: actions/setup-dotnet@v2.0.0
        with:
            dotnet-version: 3.1.*     
    
      - name: Setup .NET Core SDK 6.0.*
        uses: actions/setup-dotnet@v2.0.0
        with:
            dotnet-version: 6.0.*

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: EmitMapper Unit Tests
        run: dotnet test EmitMapper.Tests/EmitMapper.Tests.csproj --no-build --verbosity normal -p:ParallelizeTestCollections=false

      - name: Sample Unit Tests
        run: dotnet test Samples/SamplesTests/SamplesTests.csproj --no-build --verbosity normal -p:ParallelizeTestCollections=false

      #- uses: hmarr/debug-action@v2
      # Publish
      - name: publish emitmapper on version change
        id: publish_nuget_emitmapper
        #uses: rohith/publish-nuget@v2

        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: src/EmitMapper/EmitMapper.csproj          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.EmitMapper          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props 
          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0
          # Flag to toggle git tagging, enabled by default
          # tag_commit: true
          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*
          # API key to authenticate with NuGet server
          nuget_key: ${{ secrets.NUGET_API_KEY }}
          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true
          # Flag to set continue the next task when some error happened
          error_continue: true          


      - name: publish LightDataAccess on version change
        id: publish_nuget_LightDataAccess
        #uses: rohith/publish-nuget@v2
        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: Samples/LightDataAccess/LightDataAccess.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.LightDataAccess
          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props

          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0

          # Flag to toggle git tagging, enabled by default
          tag_commit: false

          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*

          # API key to authenticate with NuGet server
          nuget_key: ${{ secrets.NUGET_API_KEY }}

          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true
          # Flag to set continue the next task when some error happened
          error_continue: true
      
      - name: publish EMConfigurations on version change
        id: publish_nuget_EMConfigurations
        #uses: rohith/publish-nuget@v2
        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: Samples/EMConfigurations/EMConfigurations.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.EMConfigurations
          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props

          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0

          # Flag to toggle git tagging, enabled by default
          tag_commit: false

          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*

          # API key to authenticate with NuGet server   ${{secrets.NUGET_API_KEY}}
          nuget_key: ${{ secrets.NUGET_API_KEY }} 

          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true

          # Flag to set continue the next task when some error happened
          error_continue: true
           
    
          
      - name: publish EmitMapper.Mvc.Net on version change
        id: publish_nuget_EmitMapper_Mvc_Net
        #uses: rohith/publish-nuget@v2
        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: Samples/EmitMapper.Mvc.Net/EmitMapper.Mvc.Net.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.EmitMapper.Mvc.Net
          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props

          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0

          # Flag to toggle git tagging, enabled by default
          tag_commit: false 

          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*

          # API key to authenticate with NuGet server
          nuget_key: ${{ secrets.NUGET_API_KEY }}

          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true
          # Flag to set continue the next task when some error happened
          # error_continue: false


