name: compile & test & publish
on:
  push:
    branches:
      [ master ]
  pull_request:
    branches: [ master ] # Default release branch
  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
        
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  POWERSHELL_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  
jobs:
  publish:
    name: build, pack & publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022] #ubuntu-latest, macos-latest, windows-2019,
        cache: [ true]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache NuGet packages
        if: matrix.cache
        uses: actions/cache@v2
        with:
            path: ${{ github.workspace }}/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: ${{ runner.os }}-nuget-
          
          
      - name: Setup .NET Core SDK 6.0.*
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore -v n

      - name: Unit Tests
        run: dotnet test "DisruptiveSoftware.Cryptography/DisruptiveSoftware.Cryptography.Tests/DisruptiveSoftware.Cryptography.Tests.csproj" --no-build --verbosity normal -p:ParallelizeTestCollections=false

      

      #- uses: hmarr/debug-action@v2
      # Publish
      - name: publish DisruptiveSoftware.Cryptography
        id: publish_nuget_DisruptiveSoftware_Cryptography
        #uses: rohith/publish-nuget@v2

        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: DisruptiveSoftware.Cryptography/DisruptiveSoftware.Cryptography/DisruptiveSoftware.Cryptography.csproj
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.DisruptiveSoftware.Cryptography          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props 
          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0
          # Flag to toggle git tagging, enabled by default
          # tag_commit: true
          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*
          # API key to authenticate with NuGet server
          nuget_key: ${{ secrets.NUGET_API_KEY }}
          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true
          # Flag to set continue the next task when some error happened
          error_continue: true
          
          no_build: true

      - name: publish CertUtil\CertUtil.csproj
        id: publish_nuget_CertUtil
        #uses: rohith/publish-nuget@v2
        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: CertUtil/CertUtil.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.CertUtil
          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props

          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0

          # Flag to toggle git tagging, enabled by default
          tag_commit: false

          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*

          # API key to authenticate with NuGet server
          nuget_key: ${{ secrets.NUGET_API_KEY }}

          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true
          # Flag to set continue the next task when some error happened
          error_continue: true
          no_build: true
      
      - name: publish SSLCertBundleGenerator
        id: publish_nuget_SSLCertBundleGenerator
        #uses: rohith/publish-nuget@v2
        uses: niubilitytools/push-nuget@v1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          project_file_path: SSLCertBundleGenerator/SSLCertBundleGenerator.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          package_name: Niubility.EMConfigurations
          
          # Filepath with version info, relative to root of repository & defaults to project_file_path
          version_file_path: solution.props

          # Regex pattern to extract version info in a capturing group
          # version_regex: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores version_file_path & version_regex
          # version_static: 1.0.0

          # Flag to toggle git tagging, enabled by default
          tag_commit: false

          # Format of the git tag, [*] gets replaced with actual version
          # tag_format: v*

          # API key to authenticate with NuGet server   ${{secrets.NUGET_API_KEY}}
          nuget_key: ${{ secrets.NUGET_API_KEY }} 

          #  NuGet server uri hosting the packages, https://nuget.pkg.github.com or https://api.nuget.org. defaults to https://api.nuget.org
          nuget_source: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          include_symbols: true

          # Flag to set continue the next task when some error happened
          error_continue: true
          no_build: true
           
     